---
title: "Random Forest - Accuracy - 60%"
author: "SA"
date: "7/1/2020"
output: html_document
---
```{r}
library(dplyr)

caa <- fread("/Users/shreyaagarwal/Google Drive/Dissertation/Data/combined_news_citizen_tweets.csv", header = TRUE)

eng_tweets <- caa %>% filter(lang == "en")

  

caa <- caa[,-c(1,2)]

caa$CAA_stance <- as.factor(caa$CAA_stance)

#Read the hindi stopwords file
hi_stop <- readLines("/Users/shreyaagarwal/Google Drive/Dissertation/Data/final_stopwords.txt", encoding = "UTF-8")

#Read hinglish stopwords file
hiEng_stop <- readLines("/Users/shreyaagarwal/Google Drive/Dissertation/Data/hinglish_stopwords.txt")
```

```{r}
caa_labelled <- caa %>% filter(!is.na(CAA_stance))


set.seed(10)

caa_sample <- sample_n(caa_labelled, 8000)
```

```{r}
require(tm)  # load text mining package

sd <- VectorSource(caa_sample$text) # words vector

corpus <- Corpus(sd)  # build corpus

corpus <- tm_map(corpus, removeNumbers)  # remove numbers

corpus <- tm_map(corpus, removePunctuation) # remove puntucations

corpus <- tm_map(corpus, stripWhitespace) # remove  white spaces

corpus <- tm_map(corpus, removeWords, c(stopwords('english'), "and", "are", "the",
                                        "both", "appears", "within", "appear",
                                        "others", "clear", "right", "seen", 
                                        "well", hi_stop, hiEng_stop)) # remove stopwords

corpus <- tm_map(corpus, content_transformer(tolower)) 
```
```{r}
tdm <- DocumentTermMatrix(corpus)  # build document term matrix

tdm_sparse <- removeSparseTerms(tdm, 0.90) # remove sparse terms

tdm_dm <- as.data.frame(as.matrix(tdm_sparse)) # count matrix

tdm_df <- as.matrix((tdm_dm > 0) + 0) # binary instance matrix

tdm_df <- as.data.frame(tdm_df)

tdm_df <- cbind(tdm_df, caa_sample$CAA_stance) 
```

```{r}
tdm_sparse
```

```{r}
s <- sample(1:nrow(tdm_df), nrow(tdm_df)*(0.70), replace = FALSE) # random sampling

train <- tdm_df[s,] # training set

test <- tdm_df[-s,] # testing set

dim(train)
```

```{r}
table(train$`caa_sample$CAA_stance`)
```

```{r}
table(test$`caa_sample$CAA_stance`)
```

```{r}
library("caret")  # Load caret package

ctrl <- trainControl(method = "cv", number = 7) # 10-fold CV


set.seed(100)  

rf.tfidf <- train(train[,c(1:14)], train[,15],
                  method = "rpart", trControl = ctrl) # train random forest

rf.tfidf


```

